# Generated by Django 3.0 on 2021-12-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='usr',
            field=models.IntegerField(),
        ),
    ]
