# Generated by Django 3.0 on 2021-12-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_auto_20211211_1711'),
        ('user', '0002_auto_20211211_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='channelJoined',
            field=models.ManyToManyField(default=None, to='channels.Channel'),
        ),
    ]
